server:
  port: 9090

spring:
  application:
    name: msvc-usuario
  jpa:
    hibernate:
      ddl-auto: none
    database: sqlserver
    database-platform: org.hibernate.dialect.SQLServerDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
