spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://161.132.55.86:1433;databaseName=BD_VISHE;encrypt=false;
    username: sa
    password: Lima1234..
