server:
  port: 9090

spring:
  application:
    name: msvc-course
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=dbMicro;integratedSecurity=true;encrypt=false;
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: create
    database: sqlserver
    database-platform: org.hibernate.dialect.SQLServerDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
