server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authority
          uri: http://localhost:8090
          predicates:
           - Path=/api/authority/**
        - id: usuario
          uri: http://localhost:9090
          predicates:
           - Path=/api/usuario/**